"""create initial models

Revision ID: d918ec506172
Revises: 
Create Date: 2026-08-08 04:27:44.358915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd918ec506172'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_status_id'), 'auth_users', ['status_id'], unique=False)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=False),
    sa.Column('contact_person_name', sa.String(length=64), nullable=False),
    sa.Column('contact_person_email', sa.String(length=120), nullable=False),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_person_designation', sa.String(length=64), nullable=False),
    sa.Column('company_description', sa.String(length=256), nullable=False),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    op.create_index(op.f('ix_company_contact_person_designation'), 'company', ['contact_person_designation'], unique=False)
    op.create_index(op.f('ix_company_contact_person_email'), 'company', ['contact_person_email'], unique=True)
    op.create_index(op.f('ix_company_contact_person_name'), 'company', ['contact_person_name'], unique=False)
    op.create_index(op.f('ix_company_contact_person_phone'), 'company', ['contact_person_phone'], unique=True)
    op.create_index(op.f('ix_company_status_id'), 'company', ['status_id'], unique=False)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=True)
    op.create_table('auth_refresh_tokens',
    sa.Column('token', sa.String(length=24), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_refresh_tokens_expires_at'), 'auth_refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'auth_refresh_tokens', ['user_id'], unique=True)
    op.create_table('company_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_name', sa.String(length=64), nullable=False),
    sa.Column('branch_contact_person_name', sa.String(length=64), nullable=False),
    sa.Column('branch_contact_person_email', sa.String(length=120), nullable=False),
    sa.Column('branch_contact_person_phone', sa.String(length=20), nullable=False),
    sa.Column('branch_contact_person_designation', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_branches_branch_contact_person_designation'), 'company_branches', ['branch_contact_person_designation'], unique=False)
    op.create_index(op.f('ix_company_branches_branch_contact_person_email'), 'company_branches', ['branch_contact_person_email'], unique=True)
    op.create_index(op.f('ix_company_branches_branch_contact_person_name'), 'company_branches', ['branch_contact_person_name'], unique=False)
    op.create_index(op.f('ix_company_branches_branch_contact_person_phone'), 'company_branches', ['branch_contact_person_phone'], unique=True)
    op.create_index(op.f('ix_company_branches_branch_name'), 'company_branches', ['branch_name'], unique=False)
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=64), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_state_name'), 'state', ['state_name'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_branch_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('landmark', sa.String(length=128), nullable=False),
    sa.Column('lattitude', sa.String(length=64), nullable=False),
    sa.Column('longitude', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_branch_id'], ['company_branches.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_area'), 'address', ['area'], unique=False)
    op.create_index(op.f('ix_address_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ix_address_landmark'), 'address', ['landmark'], unique=False)
    op.create_index(op.f('ix_address_lattitude'), 'address', ['lattitude'], unique=False)
    op.create_index(op.f('ix_address_longitude'), 'address', ['longitude'], unique=False)
    op.create_index(op.f('ix_address_postal_code'), 'address', ['postal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_postal_code'), table_name='address')
    op.drop_index(op.f('ix_address_longitude'), table_name='address')
    op.drop_index(op.f('ix_address_lattitude'), table_name='address')
    op.drop_index(op.f('ix_address_landmark'), table_name='address')
    op.drop_index(op.f('ix_address_city'), table_name='address')
    op.drop_index(op.f('ix_address_area'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_state_state_name'), table_name='state')
    op.drop_table('state')
    op.drop_index(op.f('ix_company_branches_branch_name'), table_name='company_branches')
    op.drop_index(op.f('ix_company_branches_branch_contact_person_phone'), table_name='company_branches')
    op.drop_index(op.f('ix_company_branches_branch_contact_person_name'), table_name='company_branches')
    op.drop_index(op.f('ix_company_branches_branch_contact_person_email'), table_name='company_branches')
    op.drop_index(op.f('ix_company_branches_branch_contact_person_designation'), table_name='company_branches')
    op.drop_table('company_branches')
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_expires_at'), table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_company_status_id'), table_name='company')
    op.drop_index(op.f('ix_company_contact_person_phone'), table_name='company')
    op.drop_index(op.f('ix_company_contact_person_name'), table_name='company')
    op.drop_index(op.f('ix_company_contact_person_email'), table_name='company')
    op.drop_index(op.f('ix_company_contact_person_designation'), table_name='company')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_status_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
