"""add company module tables with uuid pks

Revision ID: 21e949905993
Revises: None
Create Date: 2026-08-11 12:58:12.925459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21e949905993"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=150), nullable=False),
        sa.Column("contact_person_designation", sa.String(length=100), nullable=True),
        sa.Column("contact_person_name", sa.String(length=150), nullable=True),
        sa.Column("contact_person_email", sa.String(length=150), nullable=True),
        sa.Column("contact_person_mobile_no", sa.String(length=20), nullable=True),
        sa.Column("company_description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("is_system_record", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("company_id"),
    )
    op.create_index(
        op.f("ix_companies_company_id"), "companies", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_companies_company_name"), "companies", ["company_name"], unique=False
    )
    op.create_table(
        "countries",
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("is_system_record", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("country_id"),
    )
    op.create_index(
        op.f("ix_countries_country_id"), "countries", ["country_id"], unique=False
    )
    op.create_index(
        op.f("ix_countries_country_name"), "countries", ["country_name"], unique=True
    )
    op.create_table(
        "company_branches",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_name", sa.String(length=150), nullable=False),
        sa.Column(
            "branch_contact_person_designation", sa.String(length=100), nullable=True
        ),
        sa.Column("branch_contact_person_name", sa.String(length=150), nullable=True),
        sa.Column("branch_contact_person_email", sa.String(length=150), nullable=True),
        sa.Column(
            "branch_contact_person_mobile_no", sa.String(length=20), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("is_system_record", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.company_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("branch_id"),
    )
    op.create_index(
        op.f("ix_company_branches_branch_id"),
        "company_branches",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_branches_branch_name"),
        "company_branches",
        ["branch_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_branches_company_id"),
        "company_branches",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "states",
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("state_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("is_system_record", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"], ["countries.country_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("state_id"),
    )
    op.create_index(
        op.f("ix_states_country_id"), "states", ["country_id"], unique=False
    )
    op.create_index(op.f("ix_states_state_id"), "states", ["state_id"], unique=False)
    op.create_index(
        op.f("ix_states_state_name"), "states", ["state_name"], unique=False
    )
    op.create_table(
        "addresses",
        sa.Column("address_id", sa.UUID(), nullable=False),
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("area", sa.String(length=150), nullable=True),
        sa.Column("locality", sa.String(length=150), nullable=True),
        sa.Column("landmark", sa.String(length=150), nullable=True),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("is_system_record", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["company_branches.branch_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.country_id"],
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["states.state_id"],
        ),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index(
        op.f("ix_addresses_address_id"), "addresses", ["address_id"], unique=False
    )
    op.create_index(
        op.f("ix_addresses_branch_id"), "addresses", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_addresses_country_id"), "addresses", ["country_id"], unique=False
    )
    op.create_index(
        op.f("ix_addresses_state_id"), "addresses", ["state_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_addresses_state_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_country_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_branch_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_address_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_states_state_name"), table_name="states")
    op.drop_index(op.f("ix_states_state_id"), table_name="states")
    op.drop_index(op.f("ix_states_country_id"), table_name="states")
    op.drop_table("states")
    op.drop_index(op.f("ix_company_branches_company_id"), table_name="company_branches")
    op.drop_index(
        op.f("ix_company_branches_branch_name"), table_name="company_branches"
    )
    op.drop_index(op.f("ix_company_branches_branch_id"), table_name="company_branches")
    op.drop_table("company_branches")
    op.drop_index(op.f("ix_countries_country_name"), table_name="countries")
    op.drop_index(op.f("ix_countries_country_id"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_companies_company_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_company_id"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
