-- =====================================================================
-- Seed data: Roles, permission, Role_permission
-- Generated from Atomo Processing Unit SOW (Section 5.2 + module scopes)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Roles
-- ---------------------------------------------------------------------
INSERT INTO Roles (role_id, role_name, is_deleted) VALUES (1, 'owner', 0);
INSERT INTO Roles (role_id, role_name, is_deleted) VALUES (2, 'admin', 0);
INSERT INTO Roles (role_id, role_name, is_deleted) VALUES (3, 'operator', 0);
INSERT INTO Roles (role_id, role_name, is_deleted) VALUES (4, 'viewer', 0);

-- ---------------------------------------------------------------------
-- 2. permission
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_id, name, module, action, description) VALUES (1, 'view_device_overview', 'Device', 'view', 'View device overview and health');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (2, 'edit_device_settings', 'Device', 'edit', 'Edit device name, location, timezone');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (3, 'restart_device', 'Device', 'restart', 'Restart the device');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (4, 'shutdown_device', 'Device', 'shutdown', 'Shutdown the device');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (5, 'factory_reset_device', 'Device', 'factory_reset', 'Factory reset the device');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (6, 'set_device_role', 'Device', 'set_role', 'Set device role (standalone/master/slave)');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (7, 'add_user', 'User', 'add', 'Add a new user');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (8, 'edit_user', 'User', 'edit', 'Edit an existing user');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (9, 'remove_user', 'User', 'delete', 'Remove a user');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (10, 'assign_role', 'User', 'assign_role', 'Assign or change a user''s role');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (11, 'reset_user_password', 'User', 'reset_password', 'Reset another user''s password');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (12, 'force_logout_user', 'User', 'force_logout', 'Force logout a user');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (13, 'enable_disable_user', 'User', 'enable_disable', 'Enable or disable a user');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (14, 'view_user_activity_log', 'User', 'view_activity', 'View user activity log');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (15, 'add_camera', 'Camera', 'add', 'Add a new camera');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (16, 'edit_camera', 'Camera', 'edit', 'Edit camera configuration');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (17, 'delete_camera', 'Camera', 'delete', 'Delete a camera');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (18, 'view_camera_list', 'Camera', 'view', 'View camera list and status');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (19, 'view_live_camera', 'Camera', 'live_view', 'View live camera feed / AI overlay');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (20, 'restart_camera_stream', 'Camera', 'restart_stream', 'Restart camera stream');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (21, 'assign_model_to_camera', 'Camera', 'assign_model', 'Assign AI model to camera');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (22, 'view_model_tabs', 'AI Model', 'view', 'View AI model tabs and status');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (23, 'configure_model', 'AI Model', 'configure', 'Configure threshold, zones, FPS');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (24, 'start_stop_inference', 'AI Model', 'start_stop', 'Start or stop inference');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (25, 'manage_face_database', 'AI Model', 'manage_faces', 'Enroll faces / manage face database');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (26, 'upload_custom_model', 'Custom Model', 'upload', 'Upload a custom model package');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (27, 'validate_test_model', 'Custom Model', 'validate', 'Validate and test uploaded model');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (28, 'delete_custom_model', 'Custom Model', 'delete', 'Delete or deactivate custom model');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (29, 'view_custom_models', 'Custom Model', 'view', 'View custom models');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (30, 'manage_alert_rule', 'Alerts', 'manage_rule', 'Create, edit, delete alert rule');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (31, 'view_alerts', 'Alerts', 'view', 'View alerts');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (32, 'acknowledge_alert', 'Alerts', 'acknowledge', 'Acknowledge an alert');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (33, 'escalate_alert', 'Alerts', 'escalate', 'Mark false positive / escalate alert');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (34, 'configure_notification_channel', 'Alerts', 'configure_channel', 'Configure notification channels');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (35, 'view_reports', 'Reports', 'view', 'View reports');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (36, 'export_full_report', 'Reports', 'export_full', 'Generate and export full report');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (37, 'export_limited_report', 'Reports', 'export_limited', 'Export limited report');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (38, 'schedule_report', 'Reports', 'schedule', 'Schedule recurring reports');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (39, 'view_system_logs', 'Logs', 'view_logs', 'View system/camera/model logs');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (40, 'view_audit_trail', 'Logs', 'view_audit', 'View audit trail');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (41, 'manage_slave_device', 'Devices', 'manage_slave', 'Add/remove slave device');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (42, 'view_device_consumption', 'Devices', 'view_consumption', 'View device-wise consumption');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (43, 'reconnect_slave_device', 'Devices', 'reconnect_slave', 'Reconnect/manage slave device');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (44, 'manage_network_settings', 'Settings', 'network', 'Manage network settings');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (45, 'manage_security_settings', 'Settings', 'security', 'Manage security settings (2FA, tokens, IP whitelist)');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (46, 'manage_license', 'Settings', 'license', 'Manage license');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (47, 'manage_cloud_sync', 'Settings', 'cloud_sync', 'Manage cloud sync / Atomic Centre account');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (48, 'manage_backup_restore', 'Settings', 'backup_restore', 'Backup and restore');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (49, 'manage_ota_update', 'Settings', 'ota', 'Perform OTA update');
INSERT INTO permission (permission_id, name, module, action, description) VALUES (50, 'manage_billing', 'Settings', 'billing', 'Manage billing');

-- ---------------------------------------------------------------------
-- 3. Role_permission (mapping)
-- ---------------------------------------------------------------------
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (1, 1, 1, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (2, 2, 1, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (3, 3, 1, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (4, 4, 1, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (5, 1, 2, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (6, 2, 2, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (7, 3, 2, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (8, 4, 2, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (9, 1, 3, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (10, 2, 3, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (11, 3, 3, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (12, 4, 3, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (13, 1, 4, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (14, 2, 4, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (15, 3, 4, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (16, 4, 4, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (17, 1, 5, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (18, 2, 5, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (19, 3, 5, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (20, 4, 5, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (21, 1, 6, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (22, 2, 6, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (23, 3, 6, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (24, 4, 6, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (25, 1, 7, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (26, 2, 7, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (27, 3, 7, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (28, 4, 7, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (29, 1, 8, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (30, 2, 8, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (31, 3, 8, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (32, 4, 8, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (33, 1, 9, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (34, 2, 9, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (35, 3, 9, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (36, 4, 9, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (37, 1, 10, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (38, 2, 10, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (39, 3, 10, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (40, 4, 10, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (41, 1, 11, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (42, 2, 11, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (43, 3, 11, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (44, 4, 11, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (45, 1, 12, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (46, 2, 12, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (47, 3, 12, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (48, 4, 12, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (49, 1, 13, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (50, 2, 13, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (51, 3, 13, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (52, 4, 13, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (53, 1, 14, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (54, 2, 14, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (55, 3, 14, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (56, 4, 14, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (57, 1, 15, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (58, 2, 15, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (59, 3, 15, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (60, 4, 15, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (61, 1, 16, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (62, 2, 16, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (63, 3, 16, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (64, 4, 16, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (65, 1, 17, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (66, 2, 17, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (67, 3, 17, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (68, 4, 17, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (69, 1, 18, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (70, 2, 18, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (71, 3, 18, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (72, 4, 18, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (73, 1, 19, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (74, 2, 19, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (75, 3, 19, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (76, 4, 19, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (77, 1, 20, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (78, 2, 20, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (79, 3, 20, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (80, 4, 20, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (81, 1, 21, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (82, 2, 21, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (83, 3, 21, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (84, 4, 21, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (85, 1, 22, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (86, 2, 22, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (87, 3, 22, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (88, 4, 22, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (89, 1, 23, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (90, 2, 23, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (91, 3, 23, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (92, 4, 23, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (93, 1, 24, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (94, 2, 24, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (95, 3, 24, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (96, 4, 24, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (97, 1, 25, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (98, 2, 25, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (99, 3, 25, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (100, 4, 25, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (101, 1, 26, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (102, 2, 26, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (103, 3, 26, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (104, 4, 26, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (105, 1, 27, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (106, 2, 27, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (107, 3, 27, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (108, 4, 27, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (109, 1, 28, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (110, 2, 28, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (111, 3, 28, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (112, 4, 28, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (113, 1, 29, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (114, 2, 29, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (115, 3, 29, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (116, 4, 29, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (117, 1, 30, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (118, 2, 30, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (119, 3, 30, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (120, 4, 30, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (121, 1, 31, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (122, 2, 31, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (123, 3, 31, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (124, 4, 31, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (125, 1, 32, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (126, 2, 32, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (127, 3, 32, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (128, 4, 32, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (129, 1, 33, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (130, 2, 33, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (131, 3, 33, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (132, 4, 33, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (133, 1, 34, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (134, 2, 34, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (135, 3, 34, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (136, 4, 34, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (137, 1, 35, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (138, 2, 35, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (139, 3, 35, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (140, 4, 35, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (141, 1, 36, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (142, 2, 36, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (143, 3, 36, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (144, 4, 36, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (145, 1, 37, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (146, 2, 37, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (147, 3, 37, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (148, 4, 37, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (149, 1, 38, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (150, 2, 38, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (151, 3, 38, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (152, 4, 38, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (153, 1, 39, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (154, 2, 39, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (155, 3, 39, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (156, 4, 39, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (157, 1, 40, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (158, 2, 40, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (159, 3, 40, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (160, 4, 40, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (161, 1, 41, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (162, 2, 41, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (163, 3, 41, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (164, 4, 41, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (165, 1, 42, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (166, 2, 42, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (167, 3, 42, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (168, 4, 42, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (169, 1, 43, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (170, 2, 43, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (171, 3, 43, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (172, 4, 43, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (173, 1, 44, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (174, 2, 44, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (175, 3, 44, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (176, 4, 44, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (177, 1, 45, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (178, 2, 45, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (179, 3, 45, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (180, 4, 45, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (181, 1, 46, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (182, 2, 46, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (183, 3, 46, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (184, 4, 46, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (185, 1, 47, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (186, 2, 47, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (187, 3, 47, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (188, 4, 47, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (189, 1, 48, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (190, 2, 48, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (191, 3, 48, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (192, 4, 48, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (193, 1, 49, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (194, 2, 49, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (195, 3, 49, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (196, 4, 49, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (197, 1, 50, 1, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (198, 2, 50, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (199, 3, 50, 0, 0);
INSERT INTO Role_permission (id, role_id, permission_id, is_allowed, is_deleted) VALUES (200, 4, 50, 0, 0);